- op: add
  path: /spec/template/spec/containers/0/image
  value: localhost:5001/wadm-operator:latest
- op: replace
  path: /spec/template/spec/containers/0/env/0
  value:
    name: RUST_LOG
    value: info,controller::services=debug,async_nats=warn,controller::controller=debug
